config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  # The user workflow
  get 'workflow' => 'workflow#index'
  get 'workflow/start' => 'workflow#start'
  get 'workflow/destroy' => 'workflow#destroy'
  get 'workflow/info/:class' => 'workflow#info', as: 'workflow_info',
      constraints: { class: /[A-Z][A-Za-z]+/ }
  get 'workflow/activate/:class' => 'workflow#activate',
      as: 'workflow_activate', constraints: { class: /[A-Z][A-Za-z]+/ }
  get 'workflow/fetch' => 'workflow#fetch'

  # Search/Browse page
  get 'search' => 'search#index'
  get 'search/advanced' => 'search#advanced'

  # Documents
  get 'documents/:uid/export' => 'documents#export',
      as: 'documents_export', constraints: { uid: /.*/ }
  get 'documents/:uid/citeulike' => 'documents#citeulike',
      as: 'documents_citeulike', constraints: { uid: /.*/ }

  # Datasets (per-user)
  resources :datasets, except: :edit do
    resources :tasks, module: 'datasets', path: 'tasks',
                      except: %i[edit update show] do
      member do
        get 'view/:template', action: 'view', as: 'view'
      end
    end
  end

  # User login routes
  devise_for :users,
             skip: [:sessions],
             controllers: { passwords: 'users/passwords' }
  devise_scope :user do
    # We only want users to sign in using the dropdown box on the main page,
    # not by visiting /users/sign_in, so we don't create a get 'sign_in' route
    # here.
    post 'users/sign_in' => 'devise/sessions#create', as: :user_session
    match 'users/sign_out' => 'devise/sessions#destroy',
          as: :destroy_user_session, via: Devise.mappings[:user].sign_out_via

    # User export manipulation
    get 'users/export' => 'users#export_create', as: :user_export
    delete 'users/export' => 'users#export_delete', as: ''

    # Redirect to the root after a successful user edit
    get 'users' => 'workflow#index'
  end

  scope '/users' do
    # Libraries, nested under users
    resources :libraries, module: 'users', except: :show do
      collection { get 'query' }
    end
  end

  # Static content
  get 'static/cookies' => 'static#cookies'
  post 'static/echo' => 'static#echo'
  get 'static/user_data' => 'static#user_data'

  # Static controller also is rendering favicon/logo components that invoke
  # ActiveStorage images
  get 'favicon' => 'static#favicon', format: true,
      constraints: { format: :ico }
  get 'manifest' => 'static#manifest', format: true,
      constraints: { format: :json }
  get 'browserconfig' => 'static#browserconfig', format: true,
      constraints: { format: :xml }

  # Administration pages
  get 'admin' => 'admin#index'
  get 'admin/login' => 'admin#login'
  post 'admin/login' => 'admin#login'
  delete 'admin/logout' => 'admin#logout'

  scope '/admin' do
    resources :categories, module: 'admin' do
      collection { post 'order' }
    end
    resources :snippets, module: 'admin', except: [:show]

    get 'assets' => 'admin/assets#index', as: :assets
    post 'asset/:id' => 'admin/assets#upload', as: :upload_asset
  end

  # unAPI service
  get 'unapi' => 'unapi#index'

  # List (autocomplete) service for the search pages
  get 'lists/authors' => 'lists#authors'
  get 'lists/journals' => 'lists#journals'

  # Start off on the landing/dashboard page
  root to: 'workflow#index'
end

app/controllers/search_controller.rb
# frozen_string_literal: true

# Search and browse the document database
#
# This controller displays both traditional and advanced search pages and the
# resulting lists of documents.
#
# @see RLetters::Solr::Connection.search
class SearchController < ApplicationController
  # Show the main search index page
  #
  # @return [void]
  def index
    # Get the documents
    query = RLetters::Solr::Search.params_to_query(
      RLetters::Solr::Search.permit_params(params).to_h,
      request.format != :html
    )
    @result = RLetters::Solr::Connection.search(query)
    @result_presenter = RLetters::Presenters::SearchResultPresenter.new(result: @result)

    # If this is an AJAX HTML request, render the results table rows only
    if request.format == :html && request.xhr?
      disable_browser_cache
      render :index_xhr, layout: false
    else
      render
    end
  end

  # Show the advanced search page
  #
  # @return [void]
  def advanced
    @search_fields = RLetters::Solr::Advanced.search_fields
  end
end

app/helpers/search_helper.rb
# frozen_string_literal: true

module SearchHelper
  # Get the list of facet links for one particular field
  #
  # This function takes the facets from the `Document` class, checks them
  # against the active facets, and creates a set of list items.
  #
  # @param [RLetters::Solr::Facets] facets the facets returned
  # @param [Symbol] field the field to return links for
  # @return [String] the built markup of addition links for this field
  def facet_addition_links(facets, field)
    # Get the facets for this field
    active_facets = facets.active(params)
    field_facets = (facets.sorted_for_field(field) - active_facets).take(5)

    # Build the return value
    tags = field_facets.map do |f|
      p = RLetters::Presenters::FacetPresenter.new(facet: f)

      new_facets = active_facets + [f]
      new_params = RLetters::Solr::Facets.search_params(params, new_facets)

      facet_add_link(new_params, f.hits.to_s, p.label)
    end

    safe_join(tags)
  end

  def facet_removal_links(facets)
    active_facets = facets&.active(params)
    tags = []

    # Remove all link
    if params[:categories] || params[:fq]
      remove_params = params.except(:categories, :fq)
      remove_params = RLetters::Solr::Search.permit_params(remove_params)
      tags << facet_remove_link(remove_params, I18n.t('search.index.remove_all'))
    end

    active_facets&.each do |f|
      other_facets = active_facets.reject { |x| x == f }
      other_params = RLetters::Solr::Facets.search_params(params, other_facets)

      p = RLetters::Presenters::FacetPresenter.new(facet: f)
      tags << facet_remove_link(other_params, "#{p.field_label}: #{p.label}")
    end

    safe_join(tags)
  end

  def category_addition_tree(roots = Documents::Category.roots)
    tags = roots.map do |root|
      content_tag(:li) do
        category_add_link(root)
      end
    end

    safe_join(tags)
  end

  def category_removal_links
    tags = Documents::Category.active(params).map do |category|
      facet_remove_link(
        category.toggle_search_params(params),
        "#{Documents::Category.model_name.human}: #{category.name}"
      )
    end

    safe_join(tags)
  end

  private

  def facet_add_link(params, hits, label)
    link_to params, class: 'nav-link' do
      hits = content_tag(:div, hits.to_s,
                         class: 'float-right badge badge-light bg-white mt-1')

      safe_join([hits, label])
    end
  end

  def category_add_link(category)
    link = link_to category.toggle_search_params(params), class: 'nav-link' do
      contents = [
        check_box_tag("category_#{category.to_param}",
                      '1',
                      category.enabled?(params),
                      disabled: true),
        category.name
      ]

      safe_join(contents)
    end

    tags = [link]
    if category.has_children?
      tags << content_tag(:ul, category_addition_tree(category.children))
    end

    safe_join(tags)
  end

  def facet_remove_link(params, label)
    link_to params, class: 'nav-link' do
      close = content_tag(:div, close_icon, class: 'float-right')

      safe_join([close, label])
    end
  end
end

app/views/search/_add.html.haml
.modal-dialog{ role: 'document' }
  .modal-content
    .modal-header
      %h4.modal-title= t('.header')
      %h6.text-muted= t('.subheader')
      = close_icon(dismiss: 'modal')

    - if current_user.datasets.blank?
      .modal-body
        %p= t('.no_datasets')
    - else
      = form_tag dataset_path(current_user.datasets.first), method: :patch, id: "add-form-#{document.uid.html_id}" do
        = hidden_field_tag :uid, document.uid
        .modal-body
          .form-group
            = label_tag :dataset_id, Dataset.model_name.human
            = select_tag :dataset_id, options_from_collection_for_select(current_user.datasets, 'to_param', 'name'), class: 'form-control search-add-select'

        .modal-footer
          %button.btn.btn-secondary{ data: { dismiss: 'modal' } }= t('common.cancel')
          = submit_tag t('.submit'), class: 'btn btn-success'

app/views/search/_advanced_row.html.haml
.row.advanced-row
  .col-3
    .form-group.field-group
      = label_tag :field_0, t('.field_label'), class: 'sr-only'
      = select_tag :field_0, options_for_select(fields), class: 'form-control'
  .col-6
    .form-group.value-group
      = label_tag :value_0, t('.value_label'), class: 'sr-only'
      = text_field_tag :value_0, nil, class: 'form-control'
  .col-3
    .form-group.bool-group
      .btn-group
        = link_to '#', class: 'btn btn-secondary advanced-add-button', type: 'button', aria: { label: t('.add_label') } do
          %i.fas.fa-plus
        = link_to '#', class: 'btn btn-secondary advanced-remove-button start-invisible', type: 'button', aria: { label: t('.remove_label') } do
          %i.fas.fa-minus

      = label_tag :boolean_0, t('.boolean_label'), class: 'sr-only'
      = select_tag :boolean_0, options_for_select([[t('.and'), :and], [t('.or'), :or]]), class: 'form-control start-hidden'

app/views/search/_document.html.haml
%h5
  - if document.title
    = document.title
  - else
    = t('.untitled')
%p
  - if document.authors
    = document.authors.to_s
    |
  - if document.journal
    %em #{document.journal},
  - if document.volume
    = t('.volume_abbr', volume: document.volume) + ','
  - if document.number
    = t('.number_abbr', number: document.number)
  - if document.year
    (#{document.year}),
  - if document.pages
    = t('.pages_abbr', pages: document.pages)

app/views/search/_dropdown.html.haml
- if user_signed_in?
  %h6.dropdown-header= t('.dataset_header')
  = link_to t('.single_dataset'), new_dataset_path(q: "uid:\"#{document.uid}\"", def_type: 'lucene', fq: nil), class: 'dropdown-item ajax-modal', id: "single-#{document.uid.html_id}"
  = link_to t('.add_to_dataset'), '#', class: 'dropdown-item', data: { toggle: 'modal', target: "#add-#{document.uid.html_id}-modal" }

  .dropdown-divider

- if document.doi
  = link_to t('.journal'), "http://dx.doi.org/#{document.doi}", class: 'dropdown-item'
  .dropdown-divider

%h6.dropdown-header= t('.library')

- if user_signed_in?
  - current_user.libraries.each do |library|
    = link_to t('.yours') + ' ' + library.name, "#{library.url}#{RLetters::Documents::AsOpenUrl.new(document).params}", class: 'dropdown-item'
= link_to t('.worldcat'), "http://worldcatlibraries.org/registry/gateway?#{RLetters::Documents::AsOpenUrl.new(document).params}", class: 'dropdown-item'
= link_to t('.uk_openurl'), "http://openurl.ac.uk/?#{RLetters::Documents::AsOpenUrl.new(document).params}", class: 'dropdown-item'
.dropdown-divider

%h6.dropdown-header= t('.online')

- if document.title
  = link_to t('.google'), "http://scholar.google.com/scholar?q=#{CGI.escape(document.title)}", class: 'dropdown-item'
= link_to t('.citeulike'), documents_citeulike_path(document.uid), class: 'dropdown-item'

.dropdown-divider
%h6.dropdown-header= t('.details_header')

- if document.doi
  = link_to "DOI: #{document.doi}", "http://dx.doi.org/#{document.doi}", class: 'dropdown-item small'
- if document.license_url
  = link_to t('.license', license: document.license || t('.no_license')), document.license_url, class: 'dropdown-item small'
- else
  %span.dropdown-item-text= t('.license', license: document.license || t('.no_license'))
- if document.data_source
  %span.dropdown-item-text= t('.data_source', source: document.data_source)

.dropdown-divider
%span.dropdown-item-text.small ID: #{document.id}

app/views/search/_result_table.html.haml
%table.table.table-striped.document-list
  - result.documents.each do |d|
    %tr
      %td
        %abbr.unapi-id{ title: d.uid }= ''

        .dropdown.float-right
          %button.btn.btn-outline-secondary.btn-sm.ml-1.mb-1.dropdown-toggle{ type: 'button', id: "drop-#{d.uid.html_id}", data: { toggle: 'dropdown' }, aria: { haspopup: 'true', expanded: 'false' } }
            = t('search.index.dropdown_button')
          .dropdown-menu.dropdown-menu-right{ aria: { labelledby: "drop-#{d.uid.html_id}" } }
            = render partial: 'dropdown', locals: { document: d }

        = render partial: 'document', locals: { document: d }

        -# The modal dialog box for adding this document to an existing dataset needs to be outside the dropdown menu
        - if user_signed_in?
          -# FIXME: this should probably have the fade class?
          .modal{ id: "add-#{d.uid.html_id}-modal", tabindex: '-1', role: 'dialog', aria: { hidden: 'true' } }= render partial: 'add', locals: { document: d }

  - if presenter.next_page_params(params)
    %tr
      %td.text-center
        = link_to t('search.index.more_hits'), url_for(presenter.next_page_params(params)), class: 'jscroll-next'

app/views/search/advanced.html.haml
- content_for :breadcrumbs do
  %li.breadcrumb-item= link_to t('breadcrumbs.root'), root_path
  - if user_signed_in? && current_user.workflow_active
    %li.breadcrumb-item= link_to t('breadcrumbs.workflow_start'), workflow_start_path
    %li.breadcrumb-item= link_to t('breadcrumbs.workflow_info'), workflow_info_path(current_user.workflow_class)
    %li.breadcrumb-item= link_to t('breadcrumbs.workflow_activate'), workflow_activate_path(current_user.workflow_class)
  %li.breadcrumb-item= link_to t('breadcrumbs.search_index'), search_path
  %li.breadcrumb-item.active= t('breadcrumbs.search_advanced')

.row
  .col-6
    %h1= t('.header')
    %h4.text-muted= t_md('.subheader_markdown')

.row
  .col-12
    &nbsp;

.row
  .col-12.col-md-10.offset-md-1
    = form_tag search_path, method: 'get', role: 'form' do
      = hidden_field_tag :advanced, true
      = javascript_tag("window.rlRowMarkup = '#{j render(partial: 'advanced_row', locals: { fields: @search_fields })}';", nonce: true)

      #advanced-rows
        = render partial: 'advanced_row', locals: { fields: @search_fields }

      .form-group
        = submit_tag t('.search_button'), class: 'btn btn-primary'

.row.advanced-solr
  .col-12.col-md-10.offset-md-1
    %button.btn.btn-secondary.btn-sm{ type: 'button', data: { toggle: 'collapse', target: '#solr-collapse' }, aria: { expanded: 'false', controls: 'solr-collapse' } }= t('.solr_header')

    .collapse#solr-collapse
      .card.card-body
        = form_tag search_path, method: 'get' do
          = hidden_field_tag :advanced, true

          .form-group
            = label_tag :q, t('.solr_label'), class: 'sr-only'
            = text_area_tag(:q, nil, escape: false, class: 'form-control')

          .form-group
            = submit_tag t('.solr_button'), class: 'btn btn-primary'

app/views/search/index.html.haml
- content_for :breadcrumbs do
  %li.breadcrumb-item= link_to t('breadcrumbs.root'), root_path
  - if user_signed_in? && current_user.workflow_active
    %l.breadcrumb-item= link_to t('breadcrumbs.workflow_start'), workflow_start_path
    %li.breadcrumb-item= link_to t('breadcrumbs.workflow_info'), workflow_info_path(current_user.workflow_class)
    %li.breadcrumb-item= link_to t('breadcrumbs.workflow_activate'), workflow_activate_path(current_user.workflow_class)
  %li.breadcrumb-item.active= t('breadcrumbs.search_index')

.row
  .col-7.col-lg-9
    = form_tag(search_path, method: :get, role: 'form') do
      - if @result.params['fq']
        - [@result.params['fq']].flatten.each do |p|
          = hidden_field_tag 'fq[]', p
      .form-group
        %label.sr-only{ for: 'q' }= t('.placeholder')
        = search_field_tag :q, (params[:advanced] ? t('.adv_search_placeholder') : params[:q]), placeholder: t('.placeholder'), class: 'form-control'
      %button.sr-only{ type: 'submit' }= t('.search_button')

  .col-5.col-lg-3
    .btn-group.d-flex{ role: 'group' }
      .btn-group.w-100{ role: 'group' }
        = link_to('#', class: 'btn btn-light w-100 dropdown-toggle', data: { toggle: 'dropdown' }, role: 'button', aria: { haspopup: 'true', expanded: 'false' }) do
          %i.fas.fa-sort
          = t('.sort')
        .dropdown-menu
          - @result_presenter.sort_methods.each do |(param, desc)|
            = link_to RLetters::Solr::Search.permit_params(params.merge(sort: param)), class: 'dropdown-item' do
              %span{ class: (param == @result.params['sort'] ? nil : 'start-invisible') } &check;
              = desc

      %a.btn.btn-light.w-100.d-lg-none.collapsed#filters-button{ href: '#', role: 'button', data: { toggle: 'collapse', target: '#filters' } }
        %i.fas.fa-filter
        = t('.toggle_filters')

      = link_to user_signed_in? ? new_dataset_path(q: @result.params['q'], def_type: @result.params['defType'], fq: @result.params['fq']) : '#', class: "btn btn-success w-100 #{user_signed_in? ? 'ajax-modal' : 'disabled'}", id: 'new-dataset' do
        %i.fas.fa-save
        = t('.create_dataset')

.row
  .col-12.col-lg-3.order-lg-last
    %p.text-center= @result_presenter.num_hits_string

    .collapse.d-lg-block.mb-3#filters
      .card.bg-light.card-body
        - if @result.facets || Documents::Category.count
          %h4= t('.filter_header')

          %nav.nav.nav-pills.flex-column.filter-list
            - if params[:fq].present? || Documents::Category.active(params).present?
              .filter-header= t('.active_filters')

              = facet_removal_links(@result.facets)
              = category_removal_links

            - if @result.facets
              .filter-header= t('.authors_facet')
              = facet_addition_links(@result.facets, :authors_facet)

              .filter-header= t('.journal_facet')
              = facet_addition_links(@result.facets, :journal_facet)

              .filter-header= t('.year_facet')
              = facet_addition_links(@result.facets, :year)

            - if Documents::Category.count.positive?
              .filter-header= t('.categories')
              = category_addition_tree

        = link_to t('.advanced_search'), search_advanced_path, class: 'btn btn-outline-secondary w-100'

  .col-12.col-lg-9.order-lg-first
    #jscroll= render partial: 'result_table', locals: { result: @result, presenter: @result_presenter }

.text-center#back-to-top
  = link_to t('.back_to_top'), '#', class: 'btn btn-info btn-sm'

app/views/search/index_xhr.html.haml
= render partial: 'result_table', locals: { result: @result, presenter: @result_presenter }