config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  # The user workflow
  get 'workflow' => 'workflow#index'
  get 'workflow/start' => 'workflow#start'
  get 'workflow/destroy' => 'workflow#destroy'
  get 'workflow/info/:class' => 'workflow#info', as: 'workflow_info',
      constraints: { class: /[A-Z][A-Za-z]+/ }
  get 'workflow/activate/:class' => 'workflow#activate',
      as: 'workflow_activate', constraints: { class: /[A-Z][A-Za-z]+/ }
  get 'workflow/fetch' => 'workflow#fetch'

  # Search/Browse page
  get 'search' => 'search#index'
  get 'search/advanced' => 'search#advanced'

  # Documents
  get 'documents/:uid/export' => 'documents#export',
      as: 'documents_export', constraints: { uid: /.*/ }
  get 'documents/:uid/citeulike' => 'documents#citeulike',
      as: 'documents_citeulike', constraints: { uid: /.*/ }

  # Datasets (per-user)
  resources :datasets, except: :edit do
    resources :tasks, module: 'datasets', path: 'tasks',
                      except: %i[edit update show] do
      member do
        get 'view/:template', action: 'view', as: 'view'
      end
    end
  end

  # User login routes
  devise_for :users,
             skip: [:sessions],
             controllers: { passwords: 'users/passwords' }
  devise_scope :user do
    # We only want users to sign in using the dropdown box on the main page,
    # not by visiting /users/sign_in, so we don't create a get 'sign_in' route
    # here.
    post 'users/sign_in' => 'devise/sessions#create', as: :user_session
    match 'users/sign_out' => 'devise/sessions#destroy',
          as: :destroy_user_session, via: Devise.mappings[:user].sign_out_via

    # User export manipulation
    get 'users/export' => 'users#export_create', as: :user_export
    delete 'users/export' => 'users#export_delete', as: ''

    # Redirect to the root after a successful user edit
    get 'users' => 'workflow#index'
  end

  scope '/users' do
    # Libraries, nested under users
    resources :libraries, module: 'users', except: :show do
      collection { get 'query' }
    end
  end

  # Static content
  get 'static/cookies' => 'static#cookies'
  post 'static/echo' => 'static#echo'
  get 'static/user_data' => 'static#user_data'

  # Static controller also is rendering favicon/logo components that invoke
  # ActiveStorage images
  get 'favicon' => 'static#favicon', format: true,
      constraints: { format: :ico }
  get 'manifest' => 'static#manifest', format: true,
      constraints: { format: :json }
  get 'browserconfig' => 'static#browserconfig', format: true,
      constraints: { format: :xml }

  # Administration pages
  get 'admin' => 'admin#index'
  get 'admin/login' => 'admin#login'
  post 'admin/login' => 'admin#login'
  delete 'admin/logout' => 'admin#logout'

  scope '/admin' do
    resources :categories, module: 'admin' do
      collection { post 'order' }
    end
    resources :snippets, module: 'admin', except: [:show]

    get 'assets' => 'admin/assets#index', as: :assets
    post 'asset/:id' => 'admin/assets#upload', as: :upload_asset
  end

  # unAPI service
  get 'unapi' => 'unapi#index'

  # List (autocomplete) service for the search pages
  get 'lists/authors' => 'lists#authors'
  get 'lists/journals' => 'lists#journals'

  # Start off on the landing/dashboard page
  root to: 'workflow#index'
end

app/views/admin/_backend.html.haml
.card.mb-3
  .card-body
    %h3.card-title= t('.header')

  %ul.list-group.list-group-flush
    %li.list-group-item
      %h5= t('.database')

    - if corpus_size && ping
      %li.list-group-item= t('.db_size', count: corpus_size)
      %li.list-group-item= t('.latency', count: ping)
    - else
      %li.list-group-item= t('.connection_failed')

    - if solr_info['lucene'] && solr_info['jvm']
      %li.list-group-item
        %h5= t('.solr')

      %li.list-group-item= t('.solr_version', solr_ver: solr_info['lucene']['solr-spec-version'], lucene_ver: solr_info['lucene']['lucene-spec-version'])
      %li.list-group-item= t('.java_version', java_ver: solr_info['jvm']['version'])
      %li.list-group-item= t('.memory_info', used: solr_info['jvm']['memory']['used'], free: solr_info['jvm']['memory']['free'], total: solr_info['jvm']['memory']['total'], max: solr_info['jvm']['memory']['max'])

app/views/admin/_datasets.html.haml
.card.mb-3
  .card-body
    %h3.card-title= t('.header')

    %table.table.table-striped.table-sm
      %thead
        %tr
          %th= Dataset.human_attribute_name(:name)
          %th= User.model_name.human
          %th= Dataset.human_attribute_name(:created_at)
      %tbody
        - Dataset.order('created_at desc').limit(5).each do |dataset|
          %tr
            %td= dataset.name
            %td= dataset.user
            %td= dataset.created_at

app/views/admin/_environment.html.haml
.card
  .card-body
    %h3.card-title= t('.header')

    %table.table.table-hover.table-sm
      %thead
        %tr
          %th= t('.variable')
          %th= t('.default')
          %th= t('.value')
      %tbody
        - vars.each do |key, h|
          %tr.table-secondary
            %td{ colspan: '3' }= t(key)
          - h.each do |var, default|
            %tr
              %td= var.to_s
              %td= default
              %td.break-all= ENV[var.to_s]

app/views/admin/_nav.html.haml
%nav.navbar.navbar-expand-lg.navbar-dark.bg-dark
  = link_to t('admin.index.header', app_name: ENV['APP_NAME'] || 'RLetters'), admin_path, class: 'navbar-brand'

  %button.navbar-toggler{ type: 'button', data: { toggle: 'collapse', target: '#main-nav-collapse' }, aria: { controls: 'main-nav-collapse', expanded: 'false', label: 'Toggle navigation' } }
    %span.navbar-toggler-icon

  .collapse.navbar-collapse#main-nav-collapse
    %ul.navbar-nav.mr-auto.mt-2.mt-lg-0
      %li.nav-item.dropdown
        = link_to '#', class: 'nav-link dropdown-toggle', data: { toggle: 'dropdown' }, role: 'button', aria: { haspopup: 'true', expanded: 'false' } do
          = t('admin.nav.content')
        .dropdown-menu
          = link_to Documents::Category.model_name.human(count: 100), categories_path, class: 'dropdown-item'

      %li.nav-item.dropdown
        = link_to '#', class: 'nav-link dropdown-toggle', data: { toggle: 'dropdown' }, role: 'button', aria: { haspopup: 'true', expanded: 'false' } do
          = t('admin.nav.branding')
        .dropdown-menu
          = link_to Admin::Snippet.model_name.human(count: 100), snippets_path, class: 'dropdown-item'
          = link_to Admin::Asset.model_name.human(count: 100), assets_path, class: 'dropdown-item'

    %ul.navbar-nav.mt-2.mt-lg-0
      %li.nav-item= link_to t('layouts.nav.sign_out'), admin_logout_path, method: :delete, class: 'nav-link'

app/views/admin/_tasks.html.haml
.card.mb-3
  .card-body
    %h3.card-title= t('.header')

    %table.table.table-striped.table-sm
      %thead
        %tr
          %th= Datasets::Task.human_attribute_name(:name)
          %th= Datasets::Task.human_attribute_name(:job_type)
          %th= Dataset.model_name.human
          %th= t('.status')
      %tbody
        - Datasets::Task.order('created_at desc').limit(10).each do |task|
          %tr
            %td= task.name
            %td= task.job_type
            %td= task.dataset.name
            %td
              - if task.failed
                = t('.status_failed')
              - elsif task.finished_at
                = t('.status_finished')
              - else
                = t('.status_working')

app/views/admin/_users.html.haml
.card.mb-3
  .card-body
    %h3.card-title= t('.header')

    %table.table.table-striped.table-sm
      %thead
        %tr
          %th= User.human_attribute_name(:name)
          %th= User.human_attribute_name(:last_sign_in_at)
      %tbody
        - User.order('last_sign_in_at desc').limit(5).each do |user|
          %tr
            %td= user.name
            %td= user.last_sign_in_at

app/views/admin/_workers.html.haml
.card.mb-3
  .card-body
    %h3.card-title= t('.header')

    %table.table.table-striped.table-sm
      %thead
        %tr
          %th= Admin::WorkerStats.human_attribute_name(:worker_type)
          %th= Admin::WorkerStats.human_attribute_name(:host)
          %th= Admin::WorkerStats.human_attribute_name(:pid)
          %th= Admin::WorkerStats.human_attribute_name(:started_at)
      %tbody
        - Admin::WorkerStats.all.each do |stat|
          %tr
            %td= stat.worker_type
            %td= stat.host
            %td= stat.pid
            %td= t('.duration', started: stat.started_at, duration: time_ago_in_words(stat.started_at))

app/views/admin/index.html.haml
.row.mb-3
  .col-12
    %h1= t('.header', app_name: ENV['APP_NAME'] || 'RLetters')
    %h4.text-muted= t('.subheader', app_name: ENV['APP_NAME'] || 'RLetters')

.row.mb-3
  .col-12.col-lg-6
    = render partial: 'workers'
    = render partial: 'backend', locals: { corpus_size: @corpus_size, ping: @ping, solr_info: @solr_info }

  .col-12.col-lg-6
    = render partial: 'tasks'
    = render partial: 'datasets'
    = render partial: 'users'

.row
  .col-12
    = render partial: 'environment', locals: { vars: @config_vars }

app/views/admin/login.html.haml
%h1= t('.header')
%h4.text-muted= t('.subheader')

.row
  .col-6
    = form_tag(admin_login_path, method: :post, novalidate: true, class: 'needs-validation') do
      .form-group
        = label_tag :password, t('.password'), class: 'sr-only'
        = password_field_tag :password, nil, class: 'form-control', required: true, placeholder: t('.password')
        .invalid-feedback= validation_errors_for(:admin_password, :password, true, 'admin.login.password_blank')

      .float-right= submit_tag t('.submit'), class: 'btn btn-primary'