config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  # The user workflow
  get 'workflow' => 'workflow#index'
  get 'workflow/start' => 'workflow#start'
  get 'workflow/destroy' => 'workflow#destroy'
  get 'workflow/info/:class' => 'workflow#info', as: 'workflow_info',
      constraints: { class: /[A-Z][A-Za-z]+/ }
  get 'workflow/activate/:class' => 'workflow#activate',
      as: 'workflow_activate', constraints: { class: /[A-Z][A-Za-z]+/ }
  get 'workflow/fetch' => 'workflow#fetch'

  # Search/Browse page
  get 'search' => 'search#index'
  get 'search/advanced' => 'search#advanced'

  # Documents
  get 'documents/:uid/export' => 'documents#export',
      as: 'documents_export', constraints: { uid: /.*/ }
  get 'documents/:uid/citeulike' => 'documents#citeulike',
      as: 'documents_citeulike', constraints: { uid: /.*/ }

  # Datasets (per-user)
  resources :datasets, except: :edit do
    resources :tasks, module: 'datasets', path: 'tasks',
                      except: %i[edit update show] do
      member do
        get 'view/:template', action: 'view', as: 'view'
      end
    end
  end

  # User login routes
  devise_for :users,
             skip: [:sessions],
             controllers: { passwords: 'users/passwords' }
  devise_scope :user do
    # We only want users to sign in using the dropdown box on the main page,
    # not by visiting /users/sign_in, so we don't create a get 'sign_in' route
    # here.
    post 'users/sign_in' => 'devise/sessions#create', as: :user_session
    match 'users/sign_out' => 'devise/sessions#destroy',
          as: :destroy_user_session, via: Devise.mappings[:user].sign_out_via

    # User export manipulation
    get 'users/export' => 'users#export_create', as: :user_export
    delete 'users/export' => 'users#export_delete', as: ''

    # Redirect to the root after a successful user edit
    get 'users' => 'workflow#index'
  end

  scope '/users' do
    # Libraries, nested under users
    resources :libraries, module: 'users', except: :show do
      collection { get 'query' }
    end
  end

  # Static content
  get 'static/cookies' => 'static#cookies'
  post 'static/echo' => 'static#echo'
  get 'static/user_data' => 'static#user_data'

  # Static controller also is rendering favicon/logo components that invoke
  # ActiveStorage images
  get 'favicon' => 'static#favicon', format: true,
      constraints: { format: :ico }
  get 'manifest' => 'static#manifest', format: true,
      constraints: { format: :json }
  get 'browserconfig' => 'static#browserconfig', format: true,
      constraints: { format: :xml }

  # Administration pages
  get 'admin' => 'admin#index'
  get 'admin/login' => 'admin#login'
  post 'admin/login' => 'admin#login'
  delete 'admin/logout' => 'admin#logout'

  scope '/admin' do
    resources :categories, module: 'admin' do
      collection { post 'order' }
    end
    resources :snippets, module: 'admin', except: [:show]

    get 'assets' => 'admin/assets#index', as: :assets
    post 'asset/:id' => 'admin/assets#upload', as: :upload_asset
  end

  # unAPI service
  get 'unapi' => 'unapi#index'

  # List (autocomplete) service for the search pages
  get 'lists/authors' => 'lists#authors'
  get 'lists/journals' => 'lists#journals'

  # Start off on the landing/dashboard page
  root to: 'workflow#index'
end

app/controllers/workflow_controller.rb
# frozen_string_literal: true

# Display the user's workflow through RLetters
#
# We walk the user through the process of logging in, selecting an analysis
# type to run, gathering datasets, and collecting results.  This controller
# is responsible for all of that.
class WorkflowController < ApplicationController
  layout 'full_page'
  before_action :authenticate_user!, except: :index

  # Show the introduction page or the user dashboard
  #
  # @return [void]
  def index
    @database_size = RLetters::Solr::CorpusStats.new.size || 0

    if user_signed_in?
      render 'dashboard'
    else
      render 'index'
    end
  end

  # Start running a new analysis
  #
  # @return [void]
  def start; end

  # Destroy the currently building analysis, leaving workflow mode
  #
  # @return [void]
  def destroy
    current_user.workflow_active = false
    current_user.workflow_class = nil
    current_user.workflow_datasets.clear
    current_user.save

    redirect_to workflow_path, alert: I18n.t('workflow.destroy.success')
  end

  # Show information about a job
  #
  # @return [void]
  def info
    set_workflow_parameters
  end

  # Get the user to collect datasets for a job
  #
  # @return [void]
  def activate
    set_workflow_parameters

    # Write out the class that the user has chosen
    current_user.workflow_active = true
    current_user.workflow_class = params[:class]

    # See if we've been asked to link a dataset to this job
    if params[:link_dataset_id]
      # Actually find it, which will raise an error if it's not actually a
      # dataset that the user owns
      dataset = current_user.datasets.find(params[:link_dataset_id])
      current_user.workflow_datasets << dataset.to_param
    end

    # Same for unlinking a dataset
    if params[:unlink_dataset_id]
      # Check it and raise if it's a bad dataset ID
      unless current_user.workflow_datasets.find_index(params[:unlink_dataset_id])
        raise ActiveRecord::RecordNotFound
      end

      current_user.workflow_datasets.delete(params[:unlink_dataset_id])
    end

    # Save our changes, if any, and update the workflow parameters
    current_user.save!
    set_workflow_parameters
  end

  # Allow the user to pick up data from all of their tasks
  #
  # @return [void]
  def fetch
    analysis_criteria = { datasets: { user_id: current_user.to_param } }
    tasks = Datasets::Task.joins(:dataset).where(analysis_criteria)

    if params[:terminate]
      # Delete all unfinished tasks in the DB. When their jobs next call at(),
      # they will explode.
      tasks.not_finished.readonly(false).destroy_all
      redirect_to root_path, alert: I18n.t('workflow.fetch.terminate')
      return
    end

    @pending_tasks = tasks.active.order(:created_at)
    @finished_tasks = tasks.finished.order(finished_at: :desc)
    @failed_tasks = tasks.failed.order(:created_at)

    # If this is an AJAX request, render the tasks table only
    if request.xhr?
      disable_browser_cache
      render :fetch_xhr, layout: false
    else
      render
    end
  end

  private

  # Get the current workflow details from the params
  #
  # @return [void]
  def set_workflow_parameters
    raise ActiveRecord::RecordNotFound unless params[:class]
    @klass = params[:class].safe_constantize
    raise ActiveRecord::RecordNotFound unless @klass

    @num_datasets = @klass.num_datasets
    @num_workflow_datasets = current_user.workflow_datasets.size
  end
end

app/views/workflow/activate.html.haml
- content_for :breadcrumbs do
  %li.breadcrumb-item= link_to t('breadcrumbs.root'), root_path
  %li.breadcrumb-item= link_to t('breadcrumbs.workflow_start'), workflow_start_path
  %li.breadcrumb-item= link_to t('breadcrumbs.workflow_info'), workflow_info_path(params[:class])
  %li.breadcrumb-item.active= t('breadcrumbs.workflow_activate')

.row
  .col-12
    %h1= t('.header')
    - if @num_workflow_datasets < @num_datasets
      %h4.text-muted= t('.subheader_pending')
    - else
      %h4.text-muted= t('.subheader_done')

- if @num_workflow_datasets < @num_datasets
  .row
    .col-12
      %p= t('.pending_instructions', count: @num_datasets)

.row
  .col-12
    %h3= t('.dataset_list')

    - if @num_workflow_datasets < @num_datasets
      .alert.alert-danger{ role: 'alert' }= t('.pending_count', count: (@num_datasets - @num_workflow_datasets))

    %table.table.button-table.table-striped
      %thead
        %tr
          %th.label-cell= t('.name_column')
          %th.button-cell
      %tbody
        - if @num_workflow_datasets.zero?
          %tr
            %td.label-cell= t('.no_datasets')
            %td.button-cell
        - else
          - current_user.workflow_datasets.each do |id|
            - d = Dataset.find(id)
            %tr
              %td.label-cell= d.name
              %td.button-cell= link_to t('.delete_button'), workflow_activate_path(params[:class], unlink_dataset_id: d.to_param), data: { confirm: t('.delete_confirm') }, class: 'btn btn-sm btn-danger'

- if @num_workflow_datasets < @num_datasets
  .row
    .col-12
      .btn-group
        = link_to t('.create_button'), search_path, class: 'btn btn-success'
        = link_to t('.link_button'), '#', data: { toggle: 'modal', target: '#link-modal' }, class: 'btn btn-secondary'
- else
  .row.activate-pad
    .col-12.col-lg-6.offset-lg-3
      - button_params = { class: params[:class], job_params: { other_datasets: current_user.workflow_datasets[1..-1] } }
      - if lookup_context.exists?('params', "jobs/#{params[:class].underscore}", true)
        = link_to t('.button_params'), new_dataset_task_path(current_user.workflow_dataset(0), button_params), class: 'btn btn-primary w-100'
      - else
        = link_to t('.button_start'), dataset_tasks_path(current_user.workflow_dataset(0), button_params), method: :post, class: 'btn btn-success w-100'

-# FIXME: this should probably have the fade class?
.modal#link-modal{ tabindex: '-1', role: 'dialog', aria: { hidden: 'true' } }
  .modal-dialog{ role: 'document' }
    .modal-content
      .modal-header
        %h4.modal-title= t('.link_header')
        %h6.text-muted= t('.link_subheader')
        = close_icon(dismiss: 'modal')

      - if current_user.datasets.empty?
        .modal-body
          %p= t('.link_no_datasets')
        .modal-footer
          %button.btn.btn-secondary{ data: { dismiss: 'modal' } }= t('common.cancel')
      - else
        = form_tag workflow_activate_path(params[:class]), method: :get do
          .modal-body
            .row
              .col-6
                .form-group
                  = label_tag :link_dataset_id, Dataset.model_name.human
                  = select_tag :link_dataset_id, options_from_collection_for_select(current_user.datasets, 'to_param', 'name'), class: 'form-control'

          .modal-footer
            = submit_tag t('.link_submit'), class: 'btn btn-success'
            %button.btn.btn-secondary{ data: { dismiss: 'modal' } }= t('common.cancel')

app/views/workflow/dashboard.html.haml
.row
  .col-9.offset-1
    %h1= t('.header', app_name: ENV['APP_NAME'] || 'RLetters')
    %h4.text-muted= t('.subheader', app_name: ENV['APP_NAME'] || 'RLetters')

.row.dashboard
  .col-4.offset-1
    = link_to t('.start_button'), workflow_start_path, class: 'btn btn-success w-100'
    %p= t('.start_explanation')
  .col-4
    = link_to t('.fetch_button'), workflow_fetch_path, class: 'btn btn-secondary w-100'
    %p= t('.fetch_explanation')

.row.dashboard
  .col-4.offset-3
    = link_to t('.advanced_button'), search_path, class: 'btn btn-secondary w-100'
    %p= t('.advanced_explanation')

app/views/workflow/fetch.html.haml
- content_for :breadcrumbs do
  %li.breadcrumb-item= link_to t('breadcrumbs.root'), root_path
  %li.breadcrumb-item.active= t('breadcrumbs.workflow_fetch')

.row
  .col-12
    %h1= t('.header')
    %h4.text-muted= t('.subheader')

.row
  .col-12#workflow-task-list{ data: { fetch: 'auto', fetch_url: workflow_fetch_path } }= render template: 'workflow/fetch_xhr', layout: false

app/views/workflow/fetch_xhr.html.haml
.row
  .col-12
    %h4= t('.pending_header')
    - if @pending_tasks.empty?
      %p= t('.no_pending')
    - else
      %table.table.button-table.table-striped
        %thead
          %tr
            %th.label-cell= t('datasets.tasks.index.task_column')
            %th.label-cell= Dataset.model_name.human
            %th.label-cell= t('.progress')
        %tbody
          - @pending_tasks.each do |t|
            - p = RLetters::Presenters::TaskPresenter.new(task: t)
            %tr
              %td.label-cell= t.name
              %td.label-cell= t.dataset.name
              %td.label-cell= p.status_message || t('.no_status')

      .card.text-white.bg-secondary.card-body
        %p.card-text= t_md('.pending_cancel_markdown', terminate_url: workflow_fetch_path(terminate: 'true'), email: ENV['APP_EMAIL'] || 'noreply@example.com')

.row
  .col-12
    %h4= t('.completed_header')
    - if @finished_tasks.empty? && @failed_tasks.empty?
      %p= t('.no_completed')
    - else
      %table.table.button-table.table-striped
        %thead
          %tr
            %th.label-cell= t('datasets.tasks.index.task_column')
            %th.label-cell= Dataset.model_name.human
            %th.label-cell= t('.finished_column')
            %th.button-cell= t('datasets.tasks.index.results_column')
        %tbody
          - (@finished_tasks + @failed_tasks).each do |t|
            %tr
              %td.label-cell= t.name
              %td.label-cell= t.dataset.name
              %td.label-cell= t.failed ? t('common.progress_generic_fail') : l(t.finished_at, format: :short)
              - if t.failed
                %td.button-cell= link_to t('datasets.index_xhr.delete_button'), dataset_task_path(t.dataset, t), method: :delete, class: 'btn btn-sm btn-danger', data: { confirm: t('datasets.index_xhr.delete_confirm') }
              - else
                %td.button-cell= render partial: 'datasets/tasks/task_buttons', locals: { task: t }

app/views/workflow/index.html.haml
.row
  .col-8.offset-2#markdown-landing= Admin::Snippet.render('landing')

.row
  .col-4.offset-4#landing-login
    = link_to t('.sign_up_button'), new_user_registration_path, class: 'btn btn-primary btn-lg w-100'

- if Admin::Asset.usable?('screenshot-one') && Admin::Asset.usable?('screenshot-two') && Admin::Asset.usable?('screenshot-three')
  .row
    .col-6.offset-3
      .carousel.slide#screenshot-carousel{ data: { ride: 'carousel' } }
        %ol.carousel-indicators
          %li.active{ data: { target: '#screenshot-carousel', 'slide-to': '0' } }
          %li{ data: { target: '#screenshot-carousel', 'slide-to': '1' } }
          %li{ data: { target: '#screenshot-carousel', 'slide-to': '2' } }

        .carousel-inner
          .carousel-item.active
            %img.d-block.w-100{ src: url_for(Admin::Asset.find_by(name: 'screenshot-one').file) }
            .carousel-caption.d-none.d-md-block= Admin::Snippet.render('caption-one')
          .carousel-item
            %img.d-block.w-100{ src: url_for(Admin::Asset.find_by(name: 'screenshot-two').file) }
            .carousel-caption.d-none.d-md-block= Admin::Snippet.render('caption-two')
          .carousel-item
            %img.d-block.w-100{ src: url_for(Admin::Asset.find_by(name: 'screenshot-three').file) }
            .carousel-caption.d-none.d-md-block= Admin::Snippet.render('caption-three')

        %a.carousel-control-prev{ href: '#screenshot-carousel', role: 'button', data: { slide: 'prev' } }
          %span.carousel-control-prev-icon{ aria: { hidden: 'true' } }
          %span.sr-only Previous
        %a.carousel-control-next{ href: '#screenshot-carousel', role: 'button', data: { slide: 'next' } }
          %span.carousel-control-next-icon{ aria: { hidden: 'true' } }
          %span.sr-only Next

app/views/workflow/info.html.haml
- content_for :breadcrumbs do
  %li.breadcrumb-item= link_to t('breadcrumbs.root'), root_path
  %li.breadcrumb-item= link_to t('breadcrumbs.workflow_start'), workflow_start_path
  %li.breadcrumb-item.active= t('breadcrumbs.workflow_info')

.row
  .col-12.col-lg-6.offset-lg-6
    .btn-group.d-flex{ role: 'group' }
      = link_to t('.back'), workflow_start_path, class: 'btn btn-secondary w-100'
      = link_to t('.start'), workflow_activate_path(params[:class]), class: 'btn btn-success w-100'

.row
  .col-12#markdown-info= render partial: "jobs/#{@klass.name.underscore}/info"

.row
  .col-12.col-lg-6.offset-lg-6
    .btn-group.d-flex{ role: 'group' }
      = link_to t('.back'), workflow_start_path, class: 'btn btn-secondary w-100'
      = link_to t('.start'), workflow_activate_path(params[:class]), class: 'btn btn-success w-100'

app/views/workflow/start.html.haml
- content_for :breadcrumbs do
  %li.breadcrumb-item= link_to t('breadcrumbs.root'), root_path
  %li.breadcrumb-item.active= t('breadcrumbs.workflow_start')

.row
  .col-12
    %h1= t('.header')
    %h4.text-muted= t('.subheader')

- ApplicationJob.job_list.each do |klass|
  - next unless klass.available?
  .row.questions
    .col-12
      = link_to simple_format(klass.t('.question'), {}, wrapper_tag: 'span'), workflow_info_path(klass.name.to_s), class: 'btn btn-secondary w-100'