config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  # The user workflow
  get 'workflow' => 'workflow#index'
  get 'workflow/start' => 'workflow#start'
  get 'workflow/destroy' => 'workflow#destroy'
  get 'workflow/info/:class' => 'workflow#info', as: 'workflow_info',
      constraints: { class: /[A-Z][A-Za-z]+/ }
  get 'workflow/activate/:class' => 'workflow#activate',
      as: 'workflow_activate', constraints: { class: /[A-Z][A-Za-z]+/ }
  get 'workflow/fetch' => 'workflow#fetch'

  # Search/Browse page
  get 'search' => 'search#index'
  get 'search/advanced' => 'search#advanced'

  # Documents
  get 'documents/:uid/export' => 'documents#export',
      as: 'documents_export', constraints: { uid: /.*/ }
  get 'documents/:uid/citeulike' => 'documents#citeulike',
      as: 'documents_citeulike', constraints: { uid: /.*/ }

  # Datasets (per-user)
  resources :datasets, except: :edit do
    resources :tasks, module: 'datasets', path: 'tasks',
                      except: %i[edit update show] do
      member do
        get 'view/:template', action: 'view', as: 'view'
      end
    end
  end

  # User login routes
  devise_for :users,
             skip: [:sessions],
             controllers: { passwords: 'users/passwords' }
  devise_scope :user do
    # We only want users to sign in using the dropdown box on the main page,
    # not by visiting /users/sign_in, so we don't create a get 'sign_in' route
    # here.
    post 'users/sign_in' => 'devise/sessions#create', as: :user_session
    match 'users/sign_out' => 'devise/sessions#destroy',
          as: :destroy_user_session, via: Devise.mappings[:user].sign_out_via

    # User export manipulation
    get 'users/export' => 'users#export_create', as: :user_export
    delete 'users/export' => 'users#export_delete', as: ''

    # Redirect to the root after a successful user edit
    get 'users' => 'workflow#index'
  end

  scope '/users' do
    # Libraries, nested under users
    resources :libraries, module: 'users', except: :show do
      collection { get 'query' }
    end
  end

  # Static content
  get 'static/cookies' => 'static#cookies'
  post 'static/echo' => 'static#echo'
  get 'static/user_data' => 'static#user_data'

  # Static controller also is rendering favicon/logo components that invoke
  # ActiveStorage images
  get 'favicon' => 'static#favicon', format: true,
      constraints: { format: :ico }
  get 'manifest' => 'static#manifest', format: true,
      constraints: { format: :json }
  get 'browserconfig' => 'static#browserconfig', format: true,
      constraints: { format: :xml }

  # Administration pages
  get 'admin' => 'admin#index'
  get 'admin/login' => 'admin#login'
  post 'admin/login' => 'admin#login'
  delete 'admin/logout' => 'admin#logout'

  scope '/admin' do
    resources :categories, module: 'admin' do
      collection { post 'order' }
    end
    resources :snippets, module: 'admin', except: [:show]

    get 'assets' => 'admin/assets#index', as: :assets
    post 'asset/:id' => 'admin/assets#upload', as: :upload_asset
  end

  # unAPI service
  get 'unapi' => 'unapi#index'

  # List (autocomplete) service for the search pages
  get 'lists/authors' => 'lists#authors'
  get 'lists/journals' => 'lists#journals'

  # Start off on the landing/dashboard page
  root to: 'workflow#index'
end

app/models/admin/snippet.rb
# frozen_string_literal: true

module Admin
  # Customizable bits of content
  #
  # In a few places on an RLetters site, there are various snippets of
  # information that should be customized by each site's administrator. This
  # model represents that information in the database. The list of possible
  # snippets is generated in advance, at installation time (via database
  # seeding; see the `db/seeds` directory), and these snippets may then be
  # edited in the administration panel. Content is stored in the Markdown
  # format for easy editing, and will also be passed through ERB before
  # Markdown, so any variables accessible at the time of the call will be
  # available (such as environment variables).
  #
  # @!attribute name
  #   @raise [RecordInvalid] if the name is missing (`validates :presence`)
  #   @return [String] Name of this snippet (an internal ID)
  # @!attribute language
  #   @raise [RecordInvalid] if the language is missing (`validates :presence`)
  #     or a snippet with the same name and language already exists
  #     (`validates :uniqueness`)
  #   @return [String] Language of this snippet (in Rails locale code form)
  # @!attribute content
  #   @return [String] Markdown content for this snippet
  class Snippet < ApplicationRecord
    self.table_name = 'admin_snippets'
    validates :name, presence: true
    validates :language, presence: true,
                         uniqueness: { scope: :name }

    # @return [String] Friendly name of this snippet (looked up in locale)
    def friendly_name
      ret = I18n.t("snippets.#{name}", default: '')
      return name if ret.blank?
      ret
    end

    # Render the snippet for a particular name.  This will return an empty
    # string if an invalid name is passed.
    #
    # @param [String] name The internal ID of the snippet to render (*not* the
    #   friendly name)
    # @param [Symbol] language The language of the snippet to render (defaults
    #   to current locale)
    # @return [String] HTML output of rendering this snippet to Markdown
    def self.render(name, language = nil)
      language ||= I18n.locale

      snippet = find_by(name: name, language: language)
      return '' unless snippet

      snippet.render
    end

    # Render this snippet.
    #
    # @return [String] HTML output of rendering this snippet to Markdown
    def render
      erb_page = ERB.new(content).result(binding)
      Kramdown::Document.new(erb_page).to_html.html_safe # rubocop:disable OutputSafety
    end
  end
end

app/controllers/admin/snippets_controller.rb
# frozen_string_literal: true

module Admin
  # Edit customizable content snippets
  class SnippetsController < ApplicationController
    before_action :authenticate_admin!
    layout 'admin'

    # Show all of the currently defined snippets
    #
    # @return [void]
    def index; end

    # Show the form to create a new snippet
    #
    # @return [void]
    def new
      @snippet_list = snippet_list
      @snippet = Admin::Snippet.new

      render layout: false
    end

    # Create a new snippet
    #
    # @return [void]
    def create
      # There should be at least one snippet with this name, or else we have
      # a problem
      Admin::Snippet.find_by!(name: snippet_params[:name])

      snippet = Admin::Snippet.create(snippet_params)
      if snippet.save
        redirect_to snippets_path
      else
        redirect_to snippets_path, alert: I18n.t('admin.snippets.validation_error')
      end
    end

    # Show the edit form for an existing snippet
    #
    # @return [void]
    def edit
      @snippet_list = snippet_list
      @snippet = Admin::Snippet.find(params[:id])

      render layout: false
    end

    # Update the parameters of an existing snippet
    #
    # @return [void]
    def update
      snippet = Admin::Snippet.find(params[:id])
      snippet.update!(snippet_params)
      redirect_to snippets_path
    end

    # Delete a snippet, unless it's in English
    #
    # @return [void]
    def destroy
      snippet = Admin::Snippet.find(params[:id])
      raise ActionController::ParameterMissing, :language if snippet.language == 'en'

      snippet.destroy

      redirect_to snippets_path
    end

    private

    # Return the list of acceptable snippet names
    #
    # @return [Hash] permissible snippet names, in a hash to make a form field
    def snippet_list
      Admin::Snippet.where(language: :en).each_with_object({}) do |s, ret|
        ret[s.friendly_name] = s.name
      end
    end

    # Whitelist acceptable snippet parameters
    #
    # @return [ActionController::Parameters] acceptable parameters for
    #   mass-assignment
    def snippet_params
      params.require(:admin_snippet).permit(:name, :language, :content)
    end
  end
end

app/views/admin/snippets/_form.html.haml
= form_for(snippet, url: url, method: method, html: { novalidate: true, class: 'needs-validation' }) do |f|
  .modal-body
    .form-group
      = f.label :name
      = f.select :name, options_for_select(list), {}, class: 'form-control'
      .invalid-feedback= validation_errors_for(snippet, :name, true)
    .form-group
      = f.label :language
      = f.select :language, options_for_select(I18n.locale_options_array, snippet.language), {}, class: 'form-control'
      .invalid-feedback= validation_errors_for(snippet, :language, true)

    .form-group
      = f.label :content
      = f.text_area :content, class: 'form-control', required: true, size: '50x15'

  .modal-footer
    %button.btn.btn-secondary{ data: { dismiss: 'modal' } }= t('common.cancel')
    = f.submit class: 'btn btn-primary'

app/views/admin/snippets/edit.html.haml
.modal-dialog.modal-lg{ role: 'document' }
  .modal-content
    .modal-header
      %h4.modal-title= t('.header')
      = close_icon(dismiss: 'modal')

    = render partial: 'form', locals: { snippet: @snippet, list: @snippet_list, url: snippet_path(@snippet), method: :patch }

app/views/admin/snippets/index.html.haml
.row.mb-3
  .col-12
    %h1= t('.header')
    %h4.text-muted= t('.subheader')

    .mt-3
      = t_md('.help_markdown')

.row.mb-2
  .col-12
    = link_to new_snippet_path, class: 'btn btn-secondary float-right ajax-modal' do
      %i.fas.fa-plus
      = t('.add')

.row
  .col-12
    %table.table
      %thead
        %td= Admin::Snippet.human_attribute_name(:name)
        %td= Admin::Snippet.human_attribute_name(:language)
        %td= Admin::Snippet.human_attribute_name(:content)
        %td
      %tbody
        - Admin::Snippet.all.order(:name, :language).each do |s|
          %tr
            %td= s.name
            %td= s.language
            %td= s.render
            %td
              = link_to edit_snippet_path(s), title: t('.edit'), class: 'ajax-modal' do
                %i.fas.fa-edit.text-secondary
              - if s.language != 'en'
                = link_to snippet_path(s), method: :delete, data: { confirm: t('.delete_confirm') }, title: t('.delete') do
                  %i.fas.fa-minus-circle.text-danger

app/views/admin/snippets/new.html.haml
.modal-dialog.modal-lg{ role: 'document' }
  .modal-content
    .modal-header
      %h4.modal-title= t('.header')
      = close_icon(dismiss: 'modal')

    = render partial: 'form', locals: { snippet: @snippet, list: @snippet_list, url: snippets_path, method: :post }